### ISSUE TITLE
Request for Sample Dataset to Test the Toolkit

### ISSUE THREAD

**Issue by SttlUser** [vanderschaarlab/clairvoyance2#8]
### Question

Hello,

I have gone through the documentation and I'm keen to understand the toolkit's functionalities thoroughly. However, I am currently unable to do so as the data required to run the toolkit is not open source.

Could you kindly provide a small sample dataset or suggest an alternative dataset that I could use to test and familiarize myself with the toolkit? This would greatly help in understanding its features and potential applications.

Additionally, I tried to use a custom dataset but encountered a `KeyError` during the transformation process. Here are the details:
You can find the dataset from the provided [link](https://www.kaggle.com/datasets/lihyalan/2020-corona-virus-timeseries?resource=download)
![image](https://github.com/user-attachments/assets/dc259f7c-d98b-4630-9dd9-3b0f5bf8c160)

```python
from preprocessing import ProblemMaker
from datasets import CSVLoader
import pandas as pd

# Define parameters
problem = 'online'
max_seq_len = 24
label_name = 'value'  # Update this to target column name
treatment = None
window = 4

# Load train and test datasets
data_name = 'COVID_dataset'
data_directory = '/content/clairvoyance/datasets/data/' + data_name + '/'

data_loader_training = CSVLoader(static_file=data_directory + 'static_train_data.csv',
                                 temporal_file=data_directory + 'temporal_train_data.csv')

data_loader_testing = CSVLoader(static_file=data_directory + 'static_test_data.csv',
                                temporal_file=data_directory + 'temporal_test_data.csv')

temporal_train_data = pd.read_csv(data_directory + 'temporal_train_data.csv')
temporal_test_data = pd.read_csv(data_directory + 'temporal_test_data.csv')
static_train_data = pd.read_csv(data_directory + 'static_train_data.csv')
static_test_data = pd.read_csv(data_directory + 'static_test_data.csv')

print("Temporal Train Data Columns:", temporal_train_data.columns)
print("Temporal Test Data Columns:", temporal_test_data.columns)
print("Static Train Data Columns:", static_train_data.columns)
print("Static Test Data Columns:", static_test_data.columns)

temporal_train_data = temporal_train_data.set_index(['SUBJECT_ID'])
new_temporal_train_data = temporal_train_data.iloc[:, 1:]

print("Data loader", data_loader_training)
dataset_training = data_loader_training.load()
dataset_testing = data_loader_testing.load()

print("Finish data loading.")

# Define problem
problem_maker = ProblemMaker(problem=problem, label=[label_name],
                             max_seq_len=max_seq_len, treatment=treatment, window=window)

print("Columns in training dataset:", dataset_training.columns)
print("Columns in testing dataset:", dataset_testing.columns)

dataset_training = problem_maker.fit_transform(dataset_training)
dataset_testing = problem_maker.fit_transform(dataset_testing)

# Set other parameters
metric_name = 'auc'
task = 'classification'

metric_sets = [metric_name]
metric_parameters = {'problem': problem, 'label_name': [label_name]}

print("Finish defining problem.")
```

The error message I received is:
![image](https://github.com/user-attachments/assets/c1eb46d1-e15e-4525-862e-4031a0fc37dc)

```
KeyError: "['value'] not in index"
```

It seems that the `label_name` column is not found in the dataset.

Could you please advise me on how to resolve this issue or suggest any additional steps I might need to take to preprocess the data correctly?

Thank you for your assistance.

Best regards,  
Dev

**Comment by DrShushen** [comment]
Hello.
This library is no longer maintained, please see [temporai](https://github.com/vanderschaarlab/temporai) instead.
